# Generated by Django 3.1.5 on 2021-08-20 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('encrypt_decrypt', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EncryptDecrypt',
        ),
    ]
