# Generated by Django 3.1.5 on 2021-08-20 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files_share', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
